### ISSUE TITLE
evo issue

### ISSUE THREAD

**Issue by TheOneAndOnlyPulse** [digitrp/fivem-public-board#21]
when you purchase an evo you cant put it in the garage it says you dont own it

**Comment by aethyriion** [comment]
Did you purchase an evo personally? I'm, not seeing you purchased one. Just making sure

**Comment by TheOneAndOnlyPulse** [comment]
@Cyntaax yes i did and a few others said they did last night as well and are having the same issue

**Comment by StaticSins** [comment]
I also bought an Evo but did not get full ownership. It let's you drive it without hot wiring on delivery. However no keys given so cannot lock it or store it in a garage.

**Comment by aethyriion** [comment]
https://github.com/digitrp/fivem-server/commit/52200faf716d575a34225c9416e05a83232101de should close this. The changes are available on PTR. Can you see if both of you can buy EVOs and place them in the garage?

**Comment by StaticSins** [comment]
PTR: Attempted to purchase the Evo. It attempts to deliver but only has half the wheels and a message says there's an issue with delivery. 

Attempted to mechanic repair, didn't fix the car. It does give you a key for it in the menu. 

Updated: It does drive but it does some teetering. Because it's acting like a 2 wheel motorbike.

![20191229092539_1](https://user-images.githubusercontent.com/59340090/71560351-b528f580-2a1d-11ea-98b2-dec128ca7e4f.jpg)
![20191229092648_1](https://user-images.githubusercontent.com/59340090/71560352-b823e600-2a1d-11ea-9a11-d32ea89c9182.jpg)
